version: "3"
services:
    bot:
        container_name: faculty_manager
        #image: ghcr.io/rndrmu/facultymanager:latest
        build: .
        volumes:
          - './config.json:/config.json:ro'
          - './images:/images'
          - './migrations:/migrations'
        env_file:
          - .env
        # depends_on: [database]
        networks:
            - bot
    #database:
        #container_name: database
        #image: postgres:13
        #environment: 
            #POSTGRES_USER: ${POSTGRES_USER}
            #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            #POSTGRES_DB: ${POSTGRES_DB}
        #volumes:
          #- ./migrations/faculty_manager.sql:/docker-entrypoint-initdb.d/init.sql
        #networks:
            #- bot
networks: 
    bot: {}
