version: "3"
services:
    bot:
        build: .
        volumes:
          - '$PWD/config.json:/config.json'
          - '$PWD/images:/images'
          - '$PWD/migrations:/migrations'
        environment:
            DISCORD_TOKEN: "${DISCORD_TOKEN}"
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
            PREFIX: "${PREFIX}"
            MAILUSER: "${MAILUSER}"
            MAILPW: "${MAILPW}"
            SMTP_SERVER: "${SMTP_SERVER}"
            SMTP_PORT: "${SMTP_PORT}"
            RUST_LOG: "${RUST_LOG}"
        depends_on: [database]
        network_mode: "host"
    database:
        image: postgres:13
        ports: [5432:5432]
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
          - ./migrations/faculty_manager.sql:/docker-entrypoint-initdb.d/init.sql