version: "3"
services:
  database:
    image: postgres:13
    ports: [5432:5432]
    network_mode: "host"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./migrations/faculty_manager.sql:/docker-entrypoint-initdb.d/init.sql
  keydb:
        image: eqalpha/keydb:latest
        network_mode: "host"
        command: keydb-server /etc/keydb/keydb.conf --server-threads 4
        container_name: keydb-cache
        volumes:
            - ./migrations/redis.conf:/usr/local/etc/keydb/keydb.conf
  
  influxdb:
    image: influxdb:latest
    network_mode: "host"
    ports:
      - "8086:8086"